src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 */
class Projet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="The Project Name cannot be empty")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank (message="Cant be empty")
     * @Assert\Length(min="12", minMessage="La description doit contenir au minimum 12 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="The minimum salary cannot be empty")
     */
    private $min_salaire;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="The maximum salary cannot be empty")
     */
    private $max_salaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="projets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Proposition::class, mappedBy="projet", orphanRemoval=true)
     */
    private $propositions;

   /* /**
     * @ORM\ManyToMany(targetEntity=Competence::class, mappedBy="projet")
     *//*
    private $competences;
*/
    /**
     * @ORM\OneToOne(targetEntity=Reclamation::class, mappedBy="projet", cascade={"persist", "remove"})
     */
    private $reclamation;

    /**
     * @ORM\OneToMany(targetEntity=Fichier::class, mappedBy="projet", orphanRemoval=true)
     */
    private $fichiers;

    public function __construct()
    {
        $this->propositions = new ArrayCollection();
       // $this->competences = new ArrayCollection();
        $this->fichiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMinSalaire(): ?float
    {
        return $this->min_salaire;
    }

    public function setMinSalaire(float $min_salaire): self
    {
        $this->min_salaire = $min_salaire;

        return $this;
    }

    public function getMaxSalaire(): ?float
    {
        return $this->max_salaire;
    }

    public function setMaxSalaire(float $max_salaire): self
    {
        $this->max_salaire = $max_salaire;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;
        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Proposition[]
     */
    public function getPropositions(): Collection
    {
        return $this->propositions;
    }

    public function addProposition(Proposition $proposition): self
    {
        if (!$this->propositions->contains($proposition)) {
            $this->propositions[] = $proposition;
            $proposition->setProjet($this);
        }

        return $this;
    }

    public function removeProposition(Proposition $proposition): self
    {
        if ($this->propositions->removeElement($proposition)) {
            // set the owning side to null (unless already changed)
            if ($proposition->getProjet() === $this) {
                $proposition->setProjet(null);
            }
        }

        return $this;
    }

    /*/**
     * @return Collection|Competence[]
     */
   /* public function getCompetences(): Collection
    {
        return $this->competences;
    }

    public function addCompetence(Competence $competence): self
    {
        if (!$this->competences->contains($competence)) {
            $this->competences[] = $competence;
            $competence->addProjet($this);
        }

        return $this;
    }

    public function removeCompetence(Competence $competence): self
    {
        if ($this->competences->removeElement($competence)) {
            $competence->removeProjet($this);
        }

        return $this;
    }
*/
    public function getReclamation(): ?Reclamation
    {
        return $this->reclamation;
    }

    public function setReclamation(Reclamation $reclamation): self
    {
        // set the owning side of the relation if necessary
        if ($reclamation->getProjet() !== $this) {
            $reclamation->setProjet($this);
        }

        $this->reclamation = $reclamation;

        return $this;
    }

    /**
     * @return Collection|Fichier[]
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(Fichier $fichier): self
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers[] = $fichier;
            $fichier->setProjet($this);
        }

        return $this;
    }

    public function removeFichier(Fichier $fichier): self
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getProjet() === $this) {
                $fichier->setProjet(null);
            }
        }

        return $this;
    }
    public function __toString(): string{
        return $this->nom;
    }
}

src/Form/ProjetType.php
<?php

namespace App\Form;

//use App\Entity\Competence;
use App\Entity\Projet;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\SearchSkillsType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description', TextType::class)
            ->add('min_salaire')
            ->add('max_salaire')
         /*  ->add('competences' , EntityType::class ,[
                'class' => Competence::class ,
                'query_builder' =>function (EntityRepository $er){
                    $query = $er->createQueryBuilder('c');
                    
                    return $query;
                },
                'choice_label' => 'nom',
                'placeholder' => false ,
                'multiple' => true ,
                'mapped' =>false ,
                
            
            ]);*/
            
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }

   /* public function search_project()
    {
        $form=$this->CreateFormBuilder(null)
            ->add('projet', TextType::class)
            ->add('search', SubmitType::class, [
                'attr'=> [
                    'class'=>'btn btn-primary'
                ]
            ])
            ->getForm();

    }*/
}

src/Controller/BackController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BackController extends AbstractController
{
    /**
     * @Route("/back", name="back")
     */
    public function index(): Response
    {
        return $this->render('back/back.html.twig', [
            'controller_name' => 'BackController',
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Projet;
use App\Entity\Reclamation;
use App\Form\ProjetType;
use App\Form\StatutProjType;
//use App\Entity\Competence;
use App\Form\ReclamationType;
use App\Repository\ProjetRepository;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Id;
use Symfony\Component\Security\Core\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @Route("/projet")
 */
class ProjetController extends AbstractController
{

    public function __construct(Security $security)
    {
       $this->security = $security;
    }

    /**
     * @Route("/", name="projet_index", methods={"GET"})
     */
    public function index(ProjetRepository $projetRepository): Response
    {
        $user = $this->security->getUser();
        $projet = $this->getDoctrine()->getRepository(Projet::class)->findBy(['user' =>  $user]);
        return $this->render('reclamation/jareb.html.twig', [
            'projets' => $projet ,
        ]);
    }


    /**
     * @Route("/new", name="projet_new")
     */
    public function new(Request $request, EntityManagerInterface $entityManager)
    {   

        $id=1;
        $user = $this->security->getUser();
        //$skills=$this->getDoctrine()->getRepository(Competence::class)->findAll();
        
        //$competence=$this->getDoctrine()->getRepository(Competence::class)->find(1);
        $projet = new Projet();
        $projet->setStatut('pending');
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            
          /*  foreach($request->request->get('projet') ['competences'] as $idc){
             $comp=$this->getDoctrine()->getRepository(Competence::class)->find($idc);
             $projet->addCompetence($comp);
            }*/
            $projet->setUser($user);
            //$competence->addProjet($projet);
            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('projet/new.html.twig', [
            'projet' => $projet,
            'form' => $form->createView(),
            //'skills' =>$skills,
        ]);
    }
    /**
     * @Route("/{id}/edit", name="projet_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('projet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('projet/edit.html.twig', [
            'projets' => $projet,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/del/{id}", name="projet_delete")
     */
    public function delete(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/back", name="projet_index_back", methods={"GET"})
     */
    public function index_proj_back(ProjetRepository $projetRepository): Response
    {
        $user = $this->security->getUser();
        $projet = $this->getDoctrine()->getRepository(Projet::class)->findBy(['user' =>  $user]);
        return $this->render('back/Projet/show.html.twig', [
            'projets' => $projet ,
        ]);
    }
    /**
     * @Route("/back/{id}/edit", name="projet_edit_back", methods={"GET", "POST"})
     */
    public function edit_proj_back(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StatutProjType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('projet_index_back', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/Projet/edit.html.twig', [
            'projets' => $projet,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/back/{id}", name="projet_delete_back")
     */
    public function delete_proj_back(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('projet_index_back', [], Response::HTTP_SEE_OTHER);
    }
   /* /**
     * @Route("/search", name="search")
     *//*
    public function search_project()
    {
        $form = $this->createForm(ProjetType::class);
        return $this->render('base.html.twig', [
            'form'=>$form->createView()
        ]);
    }
*/
}

templates/back/Projet/edit.html.twig
{% extends 'Back/back.html.twig' %}
{% block title %}Modifier un projet{% endblock %}

{% block content %}
    <h1>Modifier ce projet</h1>

    <main class="browse-section">
        <div class="container">
            <div class="row">
                <div class="post501">
                    {{ form_start(form)}}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="label15">Nom*</label>
                                {{ form_widget(form.nom,{'attr':{ 'placeholder': 'Name Here' ,'class': 'job-input' }})}}
                            </div>
                            <div class="form-group">
                                <label class="label15">Min_salaire*</label>
                                {{ form_widget(form.min_salaire,{'attr':{ 'placeholder': 'min salary Here' ,'class': 'job-input' }})}}
                            </div>
                            <div class="form-group">
                                <label class="label15">Max_salaire*</label>
                                {{ form_widget(form.max_salaire,{'attr':{ 'placeholder': 'max salary Here' ,'class': 'job-input' }})}}
                            </div>
                            {# <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="label15">Skills*</label>
                                    {{ form_widget(form.competences,{'attr':{ 'placeholder': 'Skills Here' ,'class': 'menu transition hidden' }})}}
                                    <div class="ui fluid multiple search selection dropdown skills-search">
                                        <input name="tags" type="hidden" value="">
                                        <i class="dropdown icon"></i>
                                        <input class="search" autocomplete="off" tabindex="0"><span class="sizer" style=""></span><div class="default text">Skills</div>
                                        <div class="menu transition hidden" tabindex="-1">
                                            <div class="item selected" data-value="angular">Angular</div>
                                            <div class="item" data-value="css">CSS</div>
                                            <div class="item" data-value="design">Graphic Design</div>
                                            <div class="item" data-value="ember">Ember</div>
                                            <div class="item" data-value="html">HTML</div>
                                            <div class="item" data-value="ia">Information Architecture</div>
                                            <div class="item" data-value="javascript">Javascript</div>
                                            <div class="item" data-value="mech">Mechanical Engineering</div>
                                            <div class="item" data-value="meteor">Meteor</div>
                                            <div class="item" data-value="node">NodeJS</div>
                                            <div class="item" data-value="plumbing">Plumbing</div>
                                            <div class="item" data-value="python">Python</div>
                                            <div class="item" data-value="rails">Rails</div>
                                            <div class="item" data-value="react">React</div>
                                            <div class="item" data-value="repair">Kitchen Repair</div>
                                            <div class="item" data-value="ruby">Ruby</div>
                                            <div class="item" data-value="ui">UI Design</div>
                                            <div class="item" data-value="ux">User Experience</div>
                                        </div>
                                    </div>
                                </div>
                            </div> #}
                            <div class="form-group">
                                <label class="label15">Description*</label>
                                {{ form_widget(form.description,{'attr':{ 'placeholder': 'Description of Project Here' ,'class': 'textarea_input' }})}}
                            </div>
                            <div style="color: red">{{ form_errors(form.description) }}</div>
                            <h5> <strong>Statut*</strong></h5>
                            {{ form_widget(form.statut,{'attr':{ 'placeholder': 'Modifier le statut' ,'class': 'job_input' }})}}
                        </div>
                        <div class="col-lg-12">
                            <button class="post_jp_btn" type="submit" formnovalidate>Modifier</button>
                        </div>
                    </div>
                    {{ form_end(form)}}
                </div>
            </div>

        </div>
        </div>
    </main>

{% endblock %}

templates/back/Projet/show.html.twig
{% extends 'Back/back.html.twig' %}
{% block title %}La liste des projets{% endblock %}

{% block content %}
    <h1>La liste des projets</h1>
    <!-- Header End -->
    <div class="title-bar">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ol class="title-bar-text">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Les projets</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Title Start -->

    <!-- Body Start -->
    <main class="browse-section">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-md-9">
                    <div class="main-heading">
                        <div class="line-shape1">
                            <img src="images/line.svg" alt="">
                        </div>
                    </div>
                    <div class="statement_table checkout_dt">
                        <div class="statement_body">
                            <div class="table-responsive-md">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Id</th>
                                        <th>Nom du projet</th>

                                        <th scope="col">Description</th>
                                        <th>Min_Salaire</th>
                                        <th>Max_Salaire</th>
                                        <th>Statut</th>
                                        <th>Actions  </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for projet in projets %}
                                        <tr>
                                            <th scope="row">
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.id }}</p>
                                                </div>
                                            </th>
                                            <td>
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.nom }}</p>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.description }}</p>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.minSalaire }}</p>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.maxSalaire }}</p>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="user_dt_trans">
                                                    <p>{{ projet.statut }}</p>
                                                </div>
                                            </td>



                                            <td>
                                                <div class="righttfooter" >
                                                    <a class="add-post" href="{{ path('projet_edit_back', {'id': projet.id}) }}">modifier</a>

                                                </div>
                                            </td>




                                            <td>

                                                <form
                                                        {% if app.user %}
                                                        method="post" action="{{ path('projet_delete_back', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this claim?');">
                                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
                                                    <button class="add-post">Supprimer</button>
                                                    {% endif %}
                                                </form>

                                            </td>

                                        </tr>


                                    {% endfor %}




                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </main>
    <!-- Body End -->




{% endblock %}